Update pkg_ref_cache_function_coverage.R
pharmaR/riskmetric pull request #185
Opened 2021-02-03 17:28 UTC by elong0527

2021-03-08 15:34 UTC, dgkf requested changes

2021-03-08 15:34 UTC, dgkf commented on R/pkg_ref_cache_function_coverage.R
>  pkg_ref_cache.function_coverage.pkg_source <- function(x, ...) {
We should rename this function as well, possibly `exprsesion_coverage`

```suggestion
pkg_ref_cache.expression_coverage.pkg_source <- function(x, ...) {
```

2021-03-08 15:34 UTC, dgkf commented on R/pkg_ref_cache_function_coverage.R
>  pkg_ref_cache.function_coverage.pkg_source <- function(x, ...) {
As well, the title should be changed to:

```r
#' Retrieve output of covr::package_coverage, tallied by expression
```

But I can't suggest changes for that line as it's outside the diff

2021-03-08 15:51 UTC, elong0527 commented
@dgkf, After this change, the code is exactly the same as in `https://github.com/pharmaR/riskmetric/blob/master/R/pkg_ref_cache_expr_coverage.R` 

Could we just remove `pkg_ref_cache_function_coverage.R` ?

2021-03-08 16:06 UTC, dgkf commented
Ah, I didn't realize we had both. That sounds good, let's get rid of this function then.

2021-03-09 02:02 UTC, closed without merging

2021-03-09 02:03 UTC, elong0527 commented
opened a new pull request #188 to address conflicts