fixed inconsistencies in the assess_has_bug_url fuction and dispatch.…
pharmaR/riskmetric pull request #259
Opened 2022-10-13 14:29 UTC by emilliman5

… There was an S3 class specific assess_ function but no dispatch, casuing documentation error when running R CMD check. Updated tests to reflect changes in the return values of the assessment functions.

It looks like a pkg_ref specific assess_has_bug_url function was created but the parent assess_has_bug_url did not use the S3 dispatch system. I maintained the new class specific function and created the proper S3 dispatch. This also required n update unit tests because the new function returns a numeric (the number of bug report urls) instead of a character string (the bug report url).

2022-12-07 17:37 UTC, elimillera requested changes
One update needed. Otherwise looks good.

2022-12-07 17:37 UTC, elimillera commented on R/pkg_ref_cache_bug_reports_url.R
> +  # .libPaths(dirname(x$path))
We can remove this. CRAN has rejected packages in the past with commented code.

2023-01-11 15:04 UTC, emilliman5 commented on R/pkg_ref_cache_bug_reports_url.R
> +  # .libPaths(dirname(x$path))
Done

2023-01-11 15:48 UTC, elimillera approved these changes

2023-01-11 15:50 UTC, merged