Fix #287 - Document metrics available by source
pharmaR/riskmetric pull request #313
Opened 2023-09-12 20:41 UTC by parmsam-pfizer

- Created vignette to start capturing this in documentation.

2023-09-12 20:46 UTC, parmsam-pfizer commented
@emilliman5 
Can you share the code you used to generate the generic calls by dispatch source in [this video](https://youtu.be/EqKhmJ1lcN8?si=41KJ9pn2w8bBmjTR&t=865)? Did you use the code you already shared in #287?

2023-09-13 15:10 UTC, emilliman5 commented
@AARON-CLARK, should we create a function to generate a table of available assessments and metrics by ref source or would a rendered vignette be sufficient?

2023-09-14 14:37 UTC, emilliman5 commented
@parmsam-pfizer here is the code to create a rudimentary table linking assessments to ref source.

ns <- getNamespaceExports("riskmetric")

    ns <- grep("^pkg_ref_cache|^assess_", ns, value = T, 
               ignore.case = T)
    ns <- sapply(ns, methods)

    ns_df <- tibble(export=unlist(ns)) %>%
      bind_rows(tibble(export=names(ns)[sapply(ns, length)==0])) %>% 
      separate(export, c("generic", "cache", "class"), 
               sep = "\\.", remove = F)

    ns_df %>% filter(grepl("assess", generic)) %>%
      select(generic, class=cache) %>%
      mutate(value=1) %>%
      pivot_wider(names_from = class, values_from = value) %>% 
      mutate(default = coalesce(default, `NA`)) %>% 
      select(generic, default, everything(), -`NA`)

2023-09-18 15:02 UTC, parmsam commented
Pasting this reference code from personal Github for a later commit: 
```{r}
library(riskmetric)
library(dplyr)
library(tibble)
library(tidyr)
library(gt)
library(gtExtras)

ns <- getNamespaceExports("riskmetric")

ns <- grep("^pkg_ref_cache|^assess_", ns, value = T, 
           ignore.case = T)
ns <- sapply(ns, methods)

ns_df <- tibble(export=unlist(ns)) %>%
  bind_rows(tibble(export=names(ns)[sapply(ns, length)==0])) %>% 
  separate(export, c("generic", "cache", "class"), 
           sep = "\\.", remove = F)

cross_tbl <- ns_df %>% filter(grepl("assess", generic)) %>%
  select(generic, class=cache) %>%
  mutate(value=1) %>%
  pivot_wider(names_from = class, values_from = value) %>% 
  mutate(default = coalesce(default, `NA`)) %>% 
  select(generic, default, everything(), -`NA`)

cross_tbl %>% 
  dplyr::mutate(
    across(c(everything(), -generic), 
           function(x) ifelse(is.na(x), "x", "check"))
  ) %>%
  gt() %>%
  gt_fa_column(
    column = c(everything(), -generic),
    palette = c(
      "check" = "#009E73", 
      "x" = "#D55E00"
    )
  )
```

2023-10-04 14:01 UTC, emilliman5 requested changes
Please add a little bit for text describing each table. Maybe add a title to the tables as well. Does not need to be extensive but a little context will help users understand what the tables mean.

2023-10-04 14:13 UTC, emilliman5 commented on vignettes/available-metrics.Rmd
> +```{r setup echo = FALSE}
need to add a "," between chunk name and parameters

2023-11-29 13:49 UTC, emilliman5 approved these changes

2023-11-29 13:49 UTC, merged